# Generated by Django 2.1.1 on 2020-03-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('price_year', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_enddate', models.DateTimeField()),
                ('newpay_year', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_month', models.DecimalField(decimal_places=2, max_digits=8)),
                ('control_enddate', models.DateTimeField()),
                ('control_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('com_mod', models.CharField(max_length=32)),
                ('kprice_start', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kprice_end', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remove_date', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buss_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('message', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ComState',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(default='正常', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Kanter',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SoleUser',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='kans',
            field=models.ManyToManyField(to='app01.Kanter'),
        ),
        migrations.AddField(
            model_name='company',
            name='soles',
            field=models.ManyToManyField(to='app01.SoleUser'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ComState'),
        ),
    ]
