# Generated by Django 2.1.1 on 2020-03-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200325_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='title',
        ),
    ]
