# Generated by Django 2.1.1 on 2020-03-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200327_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='comdepart',
            name='message',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
